# Generated by Django 5.2.8 on 2025-11-21 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('conf', 'Conferencia'), ('conc', 'Concierto'), ('sem', 'Seminario'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('privado', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='eventos_asistidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_private', 'Puede ver eventos privados')],
            },
        ),
    ]
